FROM golang:1.20.2 AS builder
LABEL maintainer="ldg55d@gmail.com"

WORKDIR /src

# set environment path
ENV PATH /go/bin:$PATH
ENV GONOSUMDB github.com/haandol
ENV GOPRIVATE github.com/haandol

# manage dependencies
COPY go.mod go.sum ./
RUN go mod download

# build
COPY . ./

ARG BUILD_TAG
ARG APP_NAME
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -trimpath -ldflags="-X main.BuildTag=$BUILD_TAG -s -w" -o /go/bin/app ./cmd/${APP_NAME}

FROM alpine:3.17 AS server
ARG GIT_COMMIT=undefined
LABEL git_commit=$GIT_COMMIT

RUN apk --no-cache add curl
RUN apk --no-cache add tzdata
RUN echo "Asia/Seoul" >  /etc/timezone

WORKDIR /
COPY --chown=0:0 --from=builder /go/bin/app /
COPY --chown=0:0 --from=builder /src/docker-entrypoint.sh /
COPY --chown=0:0 --from=builder /src/env/dev.env /.env

ARG APP_PORT
EXPOSE ${APP_PORT}

ENTRYPOINT ["/docker-entrypoint.sh"]
