@startuml architecture

!include <awslib/AWSCommon>
!include <awslib/AWSSimplified.puml>
!include <awslib/general/all.puml>
!include <awslib/Compute/all.puml>
!include <awslib/Compute/ECSContainer2.puml>
!include <awslib/Compute/ElasticContainerService.puml>
!include <awslib/Database/RDSPostgreSQLinstance.puml>
!include <awslib/Analytics/ManagedStreamingforKafka.puml>
!include <awslib/NetworkingAndContentDelivery/all.puml>

skinparam linetype polyline

package "VPC" {
  package "ECS Cluster" {
    ECSContainer2(trip, "Trip Service", " ")
    ECSContainer2(saga, "Saga Service", " ")
    ECSContainer2(car, "Car Service", " ")
    ECSContainer2(hotel, "Hotel Service", " ")
    ECSContainer2(flight, "Flight Service", " ")
  }
  ManagedStreamingforKafka(msk, "Kafka Cluster", " ")
  RDSPostgreSQLinstance(db, "RDS Database", " ")
}

User(user, "Developer", " ")

ELBApplicationLoadBalancer(alb, "LoadBalancer", " ")

user -right-> alb : HTTP /v1/trips/
alb -right-> trip 
trip --> saga
saga --> car
car --> saga

@enduml