@startuml saga

title Ideal scenario for booking a new trip

autonumber 
skinparam responseMessageBelowArrow true
actor Client as cli
participant TripSystem as trip
participant SagaSystem as saga
participant CarSystem as car
participant HotelSystem as hotel
participant FlightSystem as flight

cli -> trip : POST /v1/trip
trip --> trip : create a trip record on DB
trip -> saga : Publish command.StartSaga

saga -> car : Publish command.BookCar
activate car
car --> car: book a car for the trip
car -> saga : Publish event.CarBooked
deactivate car

saga -> hotel : Publish command.BookHotel
activate hotel
hotel --> hotel : book a hotel for the trip
hotel -> saga : Publish event.HotelBooked
deactivate hotel

saga -> flight : Publish command.BookFlight
activate flight
flight --> flight : book a flight for the trip
flight -> saga : Publish event.FlightBooked
deactivate flight

saga -> trip : Publish event.SagaEnded
trip --> trip : complete a trip and update DB

@enduml